name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest pytest-asyncio typing_extensions isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=120 --statistics --ignore W503
          black . --check --target-version=py310 --line-length=120
          isort . --check-only --profile=black --lbt=1 -l=120
      - name: Test with pytest
        run: |
          # install local module
          pip install .
          # test with Pytest
          pytest
